#!/bin/bash -eu
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export GEN_PATH=$(eval "echo $(echo \$$1_PATH | tr '[:lower:]' '[:upper:]')") # evaluates to the value of env variable uppercase($1_PATH)
mkdir -p $GEN_PATH/assets/auth
mkdir -p $GEN_PATH/assets/tls
$CC_UTILS_PATH/cli.py config attribute --cfg-type kubernetes --cfg-name gardener-setup-$1-ci --key kubeconfig > $GEN_PATH/assets/auth/kubeconfig
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name all --key shoot-creds_yaml > $GEN_PATH/shoot-creds.yaml
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key ca_crt > $GEN_PATH/assets/tls/ca.crt
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key ca_key > $GEN_PATH/assets/tls/ca.key
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key etcd-client_crt > $GEN_PATH/assets/tls/etcd-client.crt
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key etcd-client_key > $GEN_PATH/assets/tls/etcd-client.key
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key etcd-client-ca_crt > $GEN_PATH/assets/tls/etcd-client-ca.crt
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key landscape_config_yaml > $GEN_PATH/landscape_config.yaml
$CC_UTILS_PATH/cli.py config attribute --cfg-type public_ls_setup_data --cfg-name $1 --key mergeinfo_config > $GEN_PATH/mergeinfo_config
